std = "lua51"
max_line_length = 132
self = false

-- Globals the addon defines.
globals = {
  "BINDING_HEADER_MAMAFOREVER",
  "BINDING_NAME_MAMA_COMPLETE",
  "BINDING_NAME_MAMA_DISBAND",
  "BINDING_NAME_MAMA_IDENTIFY",
  "BINDING_NAME_MAMA_INVITE",
  "BINDING_NAME_MAMA_LEAD",
  "MamaForever",
  "MamaForeverSaved",
  "SLASH_MAMA1",
  "SlashCmdList",
}

-- WoW API and globals the addon only reads.
read_globals = {
  "AcceptGroup",
  "AcceptQuest",
  "bit",
  "ConfirmAcceptQuest",
  "C_ChatInfo",
  "C_GossipInfo",
  "C_PartyInfo",
  "C_QuestLog",
  "C_TaxiMap",
  "C_Timer",
  "CLASS_ICON_TCOORDS",
  "CompleteQuest",
  "CreateFrame",
  "date",
  "debugprofilestop",
  "Enum",
  "CreateMacro",
  "EditMacro",
  "GameTooltip",
  "GameTooltip_Hide",
  "GetMacroIndexByName",
  "GetMacroInfo",
  "GetNumGroupMembers",
  "GetNumQuestChoices",
  "GetQuestID",
  "GetQuestItemLink",
  "GetQuestReward",
  "GetServerTime",
  "GetTime",
  "GetUnitName",
  "hooksecurefunc",
  "InCombatLockdown",
  "IsAltKeyDown",
  "IsControlKeyDown",
  "IsInGroup",
  "IsInGuild",
  "IsInRaid",
  "IsQuestCompletable",
  "IsShiftKeyDown",
  "GetNumRoutes",
  "NumTaxiNodes",
  "QuestLogPushQuest",
  "Settings",
  "StaticPopup_Hide",
  "strsplit",
  "TakeTaxiNode",
  "TaxiNodeGetType",
  "TaxiNodeName",
  "tinsert",
  "UIParent",
  "UISpecialFrames",
  "UnitClass",
  "UnitExists",
  "UnitFactionGroup",
  "UnitGUID",
  "UnitIsGroupLeader",
  "UnitIsPlayer",
  "UnitIsUnit",
  "UNKNOWN",
  "C_Container",
  "C_Item",
  "ClearCursor",
  "ClickTradeButton",
  "CursorHasItem",
  "GetProfessionInfo",
  "GetProfessions",
  "GetTradePlayerItemInfo",
  "NUM_BAG_SLOTS",
  "TradeFrame",
  "wipe",
}
