name: Build addon zip

on:
  push:
    tags:
    - '*'

jobs:
  build:
    name: packager
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install and run Luacheck
        run: |
          sudo apt-get install luarocks
          luarocks install --local luacheck 0.23.0
          exec /home/runner/.luarocks/bin/luacheck Mama/ --no-color --config ./Mama/.luacheckrc -q
      - name: Get the packager
        run: |
          curl -s https://raw.githubusercontent.com/mooreatv/packager/v2m/release.sh > ./release.sh
          chmod 755 ./release.sh
      - name: Create Multitoc Package
        run: ./release.sh -m pkgmeta.yaml
        env:
         CF_API_KEY: ${{ secrets.CF_API_KEY }}
         GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
         WOWI_API_TOKEN: ${{ secrets.WOWI_API_TOKEN }}
         WAGO_API_TOKEN: ${{ secrets.WAGO_API_TOKEN }}
